### ISSUE TITLE
Getting 404 error while launching Streamlit dashboard

### ISSUE THREAD

**Issue by sfc-gh-ppadige** [ideonate/jhsingle-native-proxy#20]
I'm trying to launch a Streamlit dashboard on Jupyterhub-K8s (EKS) but facing `404 : Not Found You are requesting a page that does not exist!` error. I've looked in to the dashboard pod container log, I see below error, and there are no other log statements in the log file.

`INFO:tornado.application:SuperviseAndProxyHandler http_get 54223 
DEBUG:tornado.application:No user identified
DEBUG:tornado.application:Redirecting to login url: /hub/api/oauth2/authorize?client_id=jupyterhub-user-praveen.padige%2540snowflake.com-dash-dd&redirect_uri=%2Fuser%2Fpraveen.padige%40snowflake.com%2Fdash-dd%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogImFhMWUzNGU3Yjk4NjRkZDI4MTQ2ZmMzNWI2MzU0NDkzIiwgIm5leHRfdXJsIjogIi91c2VyL3ByYXZlZW4ucGFkaWdlQHNub3dmbGFrZS5jb20vZGFzaC1kZC8ifQ
ERROR:tornado.application:Uncaught exception GET /user/praveen.padige@snowflake.com/dash-dd/ (127.0.0.6)
HTTPServerRequest(protocol='http', host='jupyter-praveen-2epadige-40snowflake-2ecom--dash-2ddd.datascience-adhoc.svc.cluster.local:8888', method='GET', uri='/user/praveen.padige@snowflake.com/dash-dd/', version='HTTP/1.1', remote_ip='127.0.0.6')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/websocket.py", line 102, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 849, in http_get
    return await self.proxy(self.port, path)
  File "/opt/conda/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 843, in proxy
    return await self.oauth_proxy(port, path)
TypeError: object NoneType can't be used in 'await' expression`

Whereas same setup is working fine in Minikube, though I see the above error in the log file, Streamlit dashboard launched successfully.  

@danlester  Could you please help me find the root cause of this issue? TIA.

**Comment by danlester** [comment]
It really depends on the details of your configuration to be honest... One thing I can say is that the error you're seeing in the logs isn't a problem: https://cdsdashboards.readthedocs.io/en/stable/chapters/troubleshooting.html#dashboards-work-but-object-nonetype-error-in-logs

**Comment by sfc-gh-ppadige** [comment]
@danlester  Thanks for your response. I've realised that I've been using dynamic storage with [ReadWriteOnce] access type. At the moment we couldn't onboard storage with [ReadWriteMany] access type. As a work around, I've implemented below solution, and it is working.

- Applying podAffinity rules (to make sure notebook server pod and dashboard server pod schedule on same node so that both pods can share same volume)

- Stop notebook server and refreshing the dashboard UI worked.

**Comment by sfc-gh-ppadige** [comment]
I'm now stuck in below issue. Appreciate your suggestions.

We've integrated Jupyterhub with Okta as our OAuth. Here is the Okta configuration.

`      c.GenericOAuthenticator.update({
          'client_id': client_id,
          'client_secret': client_secret,
          'login_service': 'Okta',
          'oauth_callback_url': 'https://jxxxxxxxxxxx.com/hub/oauth_callback',
          'authorize_url': 'https://xxxx.okta.com/oauth2/v1/authorize',
          'token_url': 'https://xxxxx.okta.com/oauth2/v1/token',
          'userdata_url': 'https://xxxxx.okta.com/oauth2/v1/userinfo',
          'username_key': 'email',
          'claim_groups_key': 'groups',
          'allowed_groups': ['Jupyterhub_Admin','Jupyterhub_User','Jupyterhub_Viewer'],
          'admin_groups': 'Jupyterhub_Admin',
          'scope' : [
              'openid',
              'profile',
              'email',
              'groups',
          ]
      })`

I've created a Steamlit dashboard and shared with "All Users" option. When other users (who are alreay part of Okta groups) tried to access the dashboard  they are getting  `403 : Forbidden' error. Though I've created a `dashboardaccess` role with `access:server` scope and assigned to these Okta groups, 403 error is not resolved.  Folks are able to successfully access the dashboard only when I explicitly add them to one of the above mentioned groups using `Mange groups` UI in Admin tab.

Wondering if there is any alternate solution?

`  loadRoles:
    dashboardaccess:
      description: Read Dashboard user models
      scopes:
        - access:servers!server=dash-streamlit-demo-app
      groups:
        - Jupyterhub_Admin
        - Jupyterhub_User
        - Jupyterhub_Viewer`

**Comment by danlester** [comment]
Closing due to inactivity automatically.
