### ISSUE TITLE
py39 compat

### ISSUE THREAD

**Issue by ericdill** [ideonate/jhsingle-native-proxy#8]
Hi @danlester , thanks for this and cdsdashboards! Deployed cdsdashboards to a python 3.9 environment and got the following stack trace when trying to deploy a dashboard
```
Traceback (most recent call last):
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/websocket.py", line 103, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 724, in http_get
    return await self.proxy(self.port, path)
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 718, in proxy
    return await self.oauth_proxy(port, path)
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 673, in oauth_proxy
    return await self.core_proxy(port, path)
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 704, in core_proxy
    if not await self.ensure_process():
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/jhsingle_native_proxy/proxyhandlers.py", line 618, in ensure_process
    await proc.start()
  File "/opt/envs/system/jupyterhub/lib/python3.9/site-packages/simpervisor/process.py", line 83, in start
    with (await self._proc_lock):
TypeError: object Lock can't be used in 'await' expression
```

It's resolved by reverting back to python 3.8. Mostly wanted to let you know about future incompatibilities. Regrettably, I don't have any bandwidth to submit a PR at this time.

**Comment by danlester** [comment]
Thank you for reporting this! I'm sure there will be a workaround so I'll take a look when I get a chance...

**Comment by tdhopper** [comment]
@danlester I opened a PR to simpervisor that would fix it

**Comment by danlester** [comment]
Thank you so much @tdhopper 

I'll see if Yuvi is able to merge your PR, and perhaps release an alternative if not.
